image: ghcr.io/scrtlabs/localsecret:v1.4.0-cw-v1-beta.2

tasks:
  - before: |
      echo "Setting up Rust toolchain"
      CARGO_HOME=/home/gitpod/.cargo rustup install nightly
      rustup target add wasm32-unknown-unknown --toolchain nightly
      rustup default nightly
  - init: |
      echo "Building contract"
      cargo wasm
  - command: |
      echo "Starting faucet server"
      node /home/gitpod/faucet_server.js
  - command: |
      echo "Starting localsecret blockchain"
      cd /home/gitpod/ && SCRT_SGX_STORAGE=/opt/secret/.sgx_secrets /home/gitpod/bootstrap_init.sh false
  - command: |
      echo "Welcome to the SecretDice Contract Pathway brought to you by Secret University!"
      
vscode:
  extensions:
    - rust-lang.rust
    - serayuzgur.crates
    - bungcip.better-toml
      
jetbrains:
  intellij:
    plugins:
      - io.digiline.secretideplugin
      - org.rust.lang
      - org.toml.lang

ports:
  - port: 26657
    onOpen: ignore
  - port: 9090-9091
    onOpen: ignore
  - port: 5000
    onOpen: ignore
  - port: 1317
    onOpen: ignore
  - port: 3000
    onOpen: ignore
  - port: 24000
    onOpen: ignore
  - port: 6060
    onOpen: ignore
  - port: 1316
    onOpen: ignore
